import type { PersonaDefinition } from '../core/types.js';

export function loadPersonaRegistry(): PersonaDefinition[] {
  return [
    {
      id: 'high-quality-engaged',
      version: '1.0.0',
      active: true,
      description: 'High intent, complete profile, stable replies, premium-friendly.',
      intentProfile: 'serious',
      pacing: 'normal',
      trustBias: 'high',
      premiumPropensity: 'medium',
      irlPropensity: 'high',
      localeBias: { country: 'TR', city: 'Istanbul' },
      probabilities: { like: 0.72, reply: 0.84, ghost: 0.04, report: 0.01, premiumBuy: 0.16, planMeet: 0.58, cancelMeet: 0.05, noShow: 0.04 },
      constraints: ['no spam', 'no rapid churn', 'no trust abuse'],
    },
    {
      id: 'low-effort',
      version: '1.0.0',
      active: true,
      description: 'Low effort, sparse engagement, minimal text depth.',
      intentProfile: 'casual',
      pacing: 'slow',
      trustBias: 'medium',
      premiumPropensity: 'low',
      irlPropensity: 'low',
      localeBias: { country: 'TR', city: 'Izmir' },
      probabilities: { like: 0.38, reply: 0.28, ghost: 0.22, report: 0.02, premiumBuy: 0.02, planMeet: 0.12, cancelMeet: 0.08, noShow: 0.10 },
      constraints: ['no aggressive nudges', 'no forced meet'],
    },
    {
      id: 'fast-responder',
      version: '1.0.0',
      active: true,
      description: 'Replies quickly and keeps conversations alive.',
      intentProfile: 'mixed',
      pacing: 'fast',
      trustBias: 'high',
      premiumPropensity: 'medium',
      irlPropensity: 'medium',
      localeBias: { country: 'DE', city: 'Berlin' },
      probabilities: { like: 0.56, reply: 0.92, ghost: 0.03, report: 0.01, premiumBuy: 0.14, planMeet: 0.30, cancelMeet: 0.05, noShow: 0.04 },
      constraints: ['reply latency must stay low'],
    },
    {
      id: 'slow-responder',
      version: '1.0.0',
      active: true,
      description: 'Replies eventually, but with long pauses.',
      intentProfile: 'serious',
      pacing: 'slow',
      trustBias: 'high',
      premiumPropensity: 'low',
      irlPropensity: 'medium',
      localeBias: { country: 'TR', city: 'Ankara' },
      probabilities: { like: 0.42, reply: 0.45, ghost: 0.12, report: 0.01, premiumBuy: 0.04, planMeet: 0.20, cancelMeet: 0.09, noShow: 0.06 },
      constraints: ['no rapid-fire follow-ups'],
    },
    {
      id: 'ghoster',
      version: '1.0.0',
      active: true,
      description: 'Starts threads and then disappears.',
      intentProfile: 'casual',
      pacing: 'bursty',
      trustBias: 'low',
      premiumPropensity: 'low',
      irlPropensity: 'low',
      probabilities: { like: 0.58, reply: 0.20, ghost: 0.56, report: 0.01, premiumBuy: 0.01, planMeet: 0.06, cancelMeet: 0.12, noShow: 0.18 },
      constraints: ['ghosting must remain high', 'no IRL pressure'],
    },
    {
      id: 'over-liker',
      version: '1.0.0',
      active: true,
      description: 'Likes broadly and stresses discovery fairness.',
      intentProfile: 'casual',
      pacing: 'fast',
      trustBias: 'medium',
      premiumPropensity: 'medium',
      irlPropensity: 'low',
      probabilities: { like: 0.94, reply: 0.30, ghost: 0.16, report: 0.02, premiumBuy: 0.12, planMeet: 0.08, cancelMeet: 0.04, noShow: 0.05 },
      constraints: ['must exercise concentration cap'],
    },
    {
      id: 'selective-liker',
      version: '1.0.0',
      active: true,
      description: 'Likes a narrow high-quality set.',
      intentProfile: 'serious',
      pacing: 'normal',
      trustBias: 'high',
      premiumPropensity: 'medium',
      irlPropensity: 'high',
      probabilities: { like: 0.21, reply: 0.76, ghost: 0.04, report: 0.01, premiumBuy: 0.11, planMeet: 0.42, cancelMeet: 0.05, noShow: 0.03 },
      constraints: ['quality over throughput'],
    },
    {
      id: 'premium-buyer',
      version: '1.0.0',
      active: true,
      description: 'Pays for boosts and expects premium tone.',
      intentProfile: 'serious',
      pacing: 'normal',
      trustBias: 'high',
      premiumPropensity: 'high',
      irlPropensity: 'medium',
      probabilities: { like: 0.54, reply: 0.68, ghost: 0.06, report: 0.01, premiumBuy: 0.72, planMeet: 0.26, cancelMeet: 0.03, noShow: 0.03 },
      constraints: ['premium distortion must be visible', 'no coercive upsell'],
    },
    {
      id: 'safety-sensitive',
      version: '1.0.0',
      active: true,
      description: 'Strongly reacts to safety and verification cues.',
      intentProfile: 'serious',
      pacing: 'slow',
      trustBias: 'high',
      premiumPropensity: 'medium',
      irlPropensity: 'medium',
      probabilities: { like: 0.48, reply: 0.58, ghost: 0.10, report: 0.12, premiumBuy: 0.08, planMeet: 0.18, cancelMeet: 0.08, noShow: 0.04 },
      constraints: ['trust holds must be respected'],
    },
    {
      id: 'spammer-scammer',
      version: '1.0.0',
      active: true,
      description: 'Adversarial actor with abusive outreach patterns.',
      intentProfile: 'adversarial',
      pacing: 'bursty',
      trustBias: 'low',
      premiumPropensity: 'low',
      irlPropensity: 'low',
      probabilities: { like: 0.88, reply: 0.12, ghost: 0.04, report: 0.44, premiumBuy: 0.0, planMeet: 0.01, cancelMeet: 0.20, noShow: 0.30 },
      constraints: ['must trip trust gating'],
    },
    {
      id: 'catfish-like',
      version: '1.0.0',
      active: true,
      description: 'Identity mismatch and verification risk.',
      intentProfile: 'adversarial',
      pacing: 'normal',
      trustBias: 'low',
      premiumPropensity: 'low',
      irlPropensity: 'low',
      probabilities: { like: 0.52, reply: 0.26, ghost: 0.18, report: 0.24, premiumBuy: 0.01, planMeet: 0.02, cancelMeet: 0.14, noShow: 0.20 },
      constraints: ['verification should fail or hold'],
    },
    {
      id: 'cautious-serious',
      version: '1.0.0',
      active: true,
      description: 'Deliberate long-term dater.',
      intentProfile: 'serious',
      pacing: 'slow',
      trustBias: 'high',
      premiumPropensity: 'medium',
      irlPropensity: 'high',
      probabilities: { like: 0.32, reply: 0.66, ghost: 0.05, report: 0.02, premiumBuy: 0.09, planMeet: 0.34, cancelMeet: 0.04, noShow: 0.03 },
      constraints: ['trust-first pacing'],
    },
    {
      id: 'fast-casual',
      version: '1.0.0',
      active: true,
      description: 'Quick browse, quick reply, quick decide.',
      intentProfile: 'casual',
      pacing: 'fast',
      trustBias: 'medium',
      premiumPropensity: 'medium',
      irlPropensity: 'medium',
      probabilities: { like: 0.68, reply: 0.62, ghost: 0.10, report: 0.01, premiumBuy: 0.12, planMeet: 0.18, cancelMeet: 0.05, noShow: 0.06 },
      constraints: ['avoid heavy friction'],
    },
    {
      id: 'churn-risk',
      version: '1.0.0',
      active: true,
      description: 'Returning user with falling engagement.',
      intentProfile: 'mixed',
      pacing: 'slow',
      trustBias: 'medium',
      premiumPropensity: 'high',
      irlPropensity: 'medium',
      probabilities: { like: 0.30, reply: 0.34, ghost: 0.18, report: 0.01, premiumBuy: 0.18, planMeet: 0.14, cancelMeet: 0.08, noShow: 0.07 },
      constraints: ['rehydration not spam'],
    },
    {
      id: 'reactivated',
      version: '1.0.0',
      active: true,
      description: 'Returns after a gap and needs re-entry handling.',
      intentProfile: 'mixed',
      pacing: 'normal',
      trustBias: 'medium',
      premiumPropensity: 'medium',
      irlPropensity: 'medium',
      probabilities: { like: 0.44, reply: 0.54, ghost: 0.08, report: 0.01, premiumBuy: 0.10, planMeet: 0.16, cancelMeet: 0.04, noShow: 0.05 },
      constraints: ['state recovery must be deterministic'],
    },
    {
      id: 'low-liquidity-market',
      version: '1.0.0',
      active: true,
      description: 'Lives in a sparse market and tests bootstrapping.',
      intentProfile: 'serious',
      pacing: 'slow',
      trustBias: 'high',
      premiumPropensity: 'low',
      irlPropensity: 'medium',
      probabilities: { like: 0.24, reply: 0.48, ghost: 0.08, report: 0.01, premiumBuy: 0.03, planMeet: 0.16, cancelMeet: 0.04, noShow: 0.05 },
      constraints: ['city liquidity must stay visible'],
      localeBias: { country: 'TR', city: 'Ankara' },
    },
    {
      id: 'underexposed-hq',
      version: '1.0.0',
      active: true,
      description: 'High quality but underexposed, fairness sensitive.',
      intentProfile: 'serious',
      pacing: 'normal',
      trustBias: 'high',
      premiumPropensity: 'medium',
      irlPropensity: 'high',
      probabilities: { like: 0.52, reply: 0.78, ghost: 0.03, report: 0.01, premiumBuy: 0.10, planMeet: 0.36, cancelMeet: 0.04, noShow: 0.03 },
      constraints: ['underexposure must be detectable'],
    },
    {
      id: 'superstar-profile',
      version: '1.0.0',
      active: true,
      description: 'Attracts excessive attention and tests concentration caps.',
      intentProfile: 'mixed',
      pacing: 'normal',
      trustBias: 'high',
      premiumPropensity: 'high',
      irlPropensity: 'medium',
      probabilities: { like: 0.86, reply: 0.74, ghost: 0.05, report: 0.01, premiumBuy: 0.24, planMeet: 0.22, cancelMeet: 0.05, noShow: 0.04 },
      constraints: ['concentration cap must activate'],
    },
  ];
}
